# -*- coding: utf-8 -*-
"""
Asset Embedding Script
Description: Reads the background image, converts it to a Base64 string,
             and saves it into a Python module (src/assets.py) for embedding.
Author: Roo
"""
import base64
import os

def embed_background_image():
    """
    Finds the background image, encodes it, and writes it to src/assets.py.
    """
    print("--- Starting Asset Embedding ---")
    
    # Define paths
    source_image_path = os.path.join('assets', 'background.jpg')
    output_py_path = os.path.join('src', 'assets.py')
    
    # Ensure the src directory exists
    os.makedirs('src', exist_ok=True)

    # 1. Read the image and encode it
    try:
        print(f"Reading source image from: '{source_image_path}'")
        with open(source_image_path, "rb") as image_file:
            encoded_string = base64.b64encode(image_file.read()).decode('utf-8')
        print("Image successfully encoded to Base64.")
    except FileNotFoundError:
        print(f"❌ Error: Source image '{source_image_path}' not found. Cannot embed assets.")
        return
    except Exception as e:
        print(f"❌ An error occurred during file reading or encoding: {e}")
        return

    # 2. Write the Python file with the encoded string
    try:
        print(f"Writing Base64 string to: '{output_py_path}'")
        with open(output_py_path, "w", encoding="utf-8") as py_file:
            py_file.write("# -*- coding: utf-8 -*-\n")
            py_file.write("\"\"\"\n")
            py_file.write("This file contains the base64 encoded background image.\n")
            py_file.write("It is auto-generated by embed_assets.py.\n")
            py_file.write("Do not edit this file manually.\n")
            py_file.write("\"\"\"\n\n")
            # Using triple quotes for the multi-line string
            py_file.write(f"BACKGROUND_IMAGE_B64 = \"\"\"{encoded_string}\"\"\"\n")
        
        print(f"✅ Success! Asset embedded in '{output_py_path}'")

    except Exception as e:
        print(f"❌ An error occurred while writing the Python asset file: {e}")

if __name__ == '__main__':
    embed_background_image()